export const SKILL_LIST = {
  Development: [
    "Angular 2+",
    "Apache",
    "Bootstrap",
    "Bourbon",
    "CSS3",
    "Django",
    "Drupal",
    "Foundation",
    "Gatsby",
    "Git",
    "Grunt",
    "Gulp",
    "HTML5",
    "JavasSript",
    "jQuery",
    "Modernizr",
    "Node",
    "npm",
    "PHP",
    "Pug/Jade",
    "Python",
    "React",
    "SASS/SCSS",
    "Skeleton",
    "SQL",
    "SVG",
    "TypeScript",
    "Vue",
    "Webpack",
    "Wordpress",
  ],
  Tools: [
    "Adobe Suite",
    "After Effects",
    "Flash",
    "Framer",
    "Illustrator",
    "InDesign",
    "InVision",
    "Lightroom",
    "MAMP/LAMP",
    "Photoshop",
    "Sketch",
    "Vim",
    "VS Code",
    "XD",
  ],
  Achievments: [
    "Cisco Security - Green Belt",
    "Cisco Security - White Belt",
    "Paul Harris Fellow",
    "Spot Award - 2017",
  ],
};

export const JOB_LIST = [
  {
    company: "Booz Allen Hamilton",
    companyUrl: "https://www.boozallen.com/",
    desc:
      "Looking for design-driven development, both mobile and web. The preferred tech stack is ES6, React, Node, GraphQL.Writing scalable, non- repetitive code, reusable code.",
    end: "Present",
    location: "McLean, VA",
    position: "Developer",
    start: "Apr 2019",
  },
  {
    company: "Cisco",
    companyUrl: "https://www.cisco.com/",
    desc:
      "Created a completely dynamic Wordpress Theme used by hundreds of different partners that brands all pages and components with their personal branding (Typography, brand colors, logo, etc)",
    end: "Apr 2019",
    location: "Herndon, VA",
    position: "Engineer",
    start: "July 2018",
  },
  {
    company: "AAPA",
    companyUrl: "https://www.aapa.org/",
    desc:
      "Finished a complete website redesign in under 4 months, on a new CMS. Developed web-site mock-ups for clients to ensure quality control and client satisfaction before project development phase.Lead Designer and Developer for Annual Conference Site.",
    end: "July 2018",
    location: "Alexandria, VA",
    position: "Full-Stack Web Developer",
    start: "Oct 2016",
  },
  {
    company: "The Motley Fool",
    companyUrl: "https://www.fool.com/",
    desc:
      "Developed and Designed Microsites, Newsletters. Developed and Designed, and Email Templates. UX tests to test the usability of mobile or websites.",
    end: "Oct 2016",
    location: "Alexandria, VA",
    position: "Front-End Web Developer",
    start: "Apr 2016",
  },
  {
    company: "Total Wine & More",
    companyUrl: "https://www.totalwine.com/",
    desc:
      "Responsible for designing and maintaining web banners in various formats to be displayed on any device, that were analyzed using Google Analytics and Google AdWords.",
    end: "Apr 2016",
    location: "Bethesda, MD",
    position: "Digital Media Designer",
    start: "Nov 2015",
  },
];
